convert KEGGgraph.Rnw to KEGGgraph.Rmd
Accio/KEGGgraph pull request #16
Opened 2023-08-18 14:05 UTC by sonali8434

@jwokaty kindly Review this PR before we ask @Accio for a final review.

@Accio We noticed that this pdf contains sections referring to pages, but it is not possible to refer to pages in new .Rmd file since we don't have a page no in an HTML document. So we have referred to sections instead of pages in the new KEGGgraph.Rmd file. If you have any suggestions about this, please don't hesitate to let us know.

We generally ask one of our team members to review the conversions before asking the maintainers to review them.

@Accio Generally, we give credits to the converter for converting Sweave documents. We ask maintainers if they want us to add ourselves as contributors in the description file and the. Rmd file. I wanted to ask if you would like me to add as a contributor for this conversion. It's totally fine to say no.

After your final review when you merge the PR, remember to bump the version in the DESCRIPTION file so that the Bioconductor build system will recognize the new changes and [push the changes to Bioconductor's git repository](https://contributions.bioconductor.org/git-version-control.html#push-to-github-bioc).

2023-08-18 22:50 UTC, jwokaty commented on vignettes/KEGGgraph.Rmd
> +REST web service ((https://rest.kegg.jp/)) without license permission for
This should have one set of parenthesis.

2023-08-18 22:50 UTC, jwokaty commented on vignettes/KEGGgraph.Rmd
> +  * Automatic retrieval from KEGG REST API, available at (https://rest.kegg.jp),
Remove the parentheses from URLs in lines 91 and 92.

2023-08-18 22:52 UTC, jwokaty commented on vignettes/KEGGgraph.Rmd
> +(https://genome.jp/kegg), or found with any search engine.
Remove parenthesis

2023-08-18 23:03 UTC, jwokaty commented on vignettes/KEGGgraph.Rmd
> +GeneID. More details on the conversion of IDs can be found on section [Annotation](#convertId)
Let's improve the wording a little with `in the [Annotation section](#convertId).` and add a full stop at the end.

2023-08-18 23:15 UTC, jwokaty commented on vignettes/KEGGgraph.Rmd
> +(http://www.bioconductor.org/packages/release/data/annotation/). To demonstrate
Remove parenthesis

2023-08-18 23:15 UTC, jwokaty commented on vignettes/KEGGgraph.Rmd
> +its use, we draw the sub-network in the figure [2](fig:02) again, whereas nodes
The link doesn't work; maybe it's missing the `#`?

2023-08-18 23:18 UTC, jwokaty commented on vignettes/KEGGgraph.Rmd
> +`r Biocpkg("RBGL")`. Therefore the execution has been suppressed for now.
@Accio I just wanted to make a note of this section that references RBGL 1.59.5 (it's now 1.79.0).

2023-08-18 23:36 UTC, jwokaty requested changes
@sonali8434  Thanks for this PR. I've made some small inline requests. The DESCRIPTION file should have `VignetteBuilder: knitr` and `BiocStyle, knitr` in Suggests. Because this is missing, `R CMD build` isn't generating the vignette.

I also want to confirm with @Accio if the new bibliography format is suitable as it presents the reference differently. For example

Current:

[Aittokallio and Schwikowski, 2006] Aittokallio and Schwikowski (2006) Graph-based methods for analysing networks in cell biology, _Briefings in Bioinformatics_, **7**, 243-255.

Newer:

Aittokallio and Schwikowski (2006) Graph-based methods for analysing networks in cell biology. _Briefings in Bioinformatics,_ **7**, 243–255.

2023-08-19 06:53 UTC, sonali8434 commented
@jwokaty Thanks for the review, and I'm sorry for not pushing my changes to the description file. Thanks for reminding me. 

I have made the changes you asked for. Please review.

2023-08-22 13:47 UTC, jwokaty approved these changes
@sonali8434 Thanks for the changes. This is ready for @Accio.

2023-08-22 13:59 UTC, Accio commented
Dear @sonali8434 and @jwokaty, I agree with the changes you proposed. Thank you for making them.

Do you mind adding yourself as contributors in the DESCRIPTION file? I am glad to merge the changes once the testing passes.

Have a good day and thanks again for the generous help, David.

2023-08-25 00:09 UTC, sonali8434 commented
@Accio, I have completed the remaining changes. Please review the file and let me know if any more changes are required.

Thank you.

2026-09-20 11:33 UTC, Accio commented
I integrated the changes and updated the contribution list. Thank you! Let me know if you have questions.

2026-09-20 11:33 UTC, closed without merging